### ISSUE TITLE
ijOKPJGISOFUIHSJFIJKSA,KFJSDMIKJFN

### ISSUE THREAD

**Issue by stalechilibeans** [codenamelonghorn/b-rollys#1]
sdgafs

**Comment by codenamelonghorn** [comment]
Bitc

**Comment by stalechilibeans** [comment]
when cagas en el monte y vuelves y tu cacota ya no esta :vvvvvv

**Comment by codenamelonghorn** [comment]
> when cagas en el monte y vuelves y tu cacota ya no esta :vvvvvv

bro respeta ni javier.rodriguez090 diría eso
